version: "3.9"

services:
  db:
    image: postgres:16
    env_file:
    - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - flight_manager_default

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    networks:
      - flight_manager_default

  backend:
    build: ./backend
    volumes:
      - ./backend:/app:cached
    ports:
      - "8000:8000"
    env_file:
    - .env
    depends_on:
      - db
      - redis
    networks:
      - flight_manager_default

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
    - .env
    depends_on:
      - backend
    networks:
      - flight_manager_default

  celery_worker:
    build: ./backend
    command: celery -A flight_manager worker --loglevel=info
    volumes:
      - ./backend:/app:cached
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    networks:
      - flight_manager_default

  celery_beat:
    build: ./backend
    command: celery -A flight_manager beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app:cached
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    networks:
      - flight_manager_default

volumes:
  db_data:

networks:
  flight_manager_default:
    driver: bridge
